/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank2;

import javax.swing.JOptionPane;

/**
 *
 * @author Salsadila
 */
public class bank extends javax.swing.JFrame {

    /**
     * Creates new form bank
     */
    public bank() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bsaldo = new javax.swing.JButton();
        bsetor = new javax.swing.JButton();
        btarik = new javax.swing.JButton();
        btransfer = new javax.swing.JButton();
        show = new javax.swing.JLabel();
        tfsetor = new javax.swing.JTextField();
        tftarik = new javax.swing.JTextField();
        show2 = new javax.swing.JLabel();
        tftransfer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel3.setText("\"Siap Melayani Dengan Sepenuh Hati\"");

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\pic\\0fb9e438bf292df2141c58fe0751ebd1.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Bank Ku");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 10, 110, 29);

        bsaldo.setText("Informasi Saldo");
        bsaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaldoActionPerformed(evt);
            }
        });
        getContentPane().add(bsaldo);
        bsaldo.setBounds(20, 70, 130, 40);

        bsetor.setText("Penyetoran");
        bsetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsetorActionPerformed(evt);
            }
        });
        getContentPane().add(bsetor);
        bsetor.setBounds(20, 140, 130, 40);

        btarik.setText("Penarikan");
        btarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btarikActionPerformed(evt);
            }
        });
        getContentPane().add(btarik);
        btarik.setBounds(20, 210, 130, 40);

        btransfer.setText("Transfer");
        btransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btransferActionPerformed(evt);
            }
        });
        getContentPane().add(btransfer);
        btransfer.setBounds(20, 280, 130, 40);

        show.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(show);
        show.setBounds(370, 70, 170, 40);
        getContentPane().add(tfsetor);
        tfsetor.setBounds(180, 140, 170, 40);
        getContentPane().add(tftarik);
        tftarik.setBounds(180, 210, 170, 40);

        show2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        show2.setText("Sisa saldo anda : Rp");
        getContentPane().add(show2);
        show2.setBounds(180, 70, 190, 40);
        getContentPane().add(tftransfer);
        tftransfer.setBounds(180, 280, 170, 40);

        jLabel4.setText("\"Siap Melayani Dengan Sepenuh Hati\"");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 40, 200, 14);

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\pic\\0fb9e438bf292df2141c58fe0751ebd1.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-100, 0, 780, 370);

        setBounds(0, 0, 679, 375);
    }// </editor-fold>//GEN-END:initComponents

    private void bsaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaldoActionPerformed
        // TODO add your handling code here:
        int saldo = 1000000;
        show.setText(""+saldo);
    }//GEN-LAST:event_bsaldoActionPerformed

    private void bsetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsetorActionPerformed
        // TODO add your handling code here:
        String setor = tfsetor.getText();
        String saldolast = show.getText();
        show.setText(""+saldolast);
        int jmlsetor = Integer.parseInt(setor);
        int lastsaldo = Integer.parseInt(saldolast);
        int total = lastsaldo+jmlsetor;
        show.setText(""+total);
    }//GEN-LAST:event_bsetorActionPerformed

    private void btarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btarikActionPerformed
        // TODO add your handling code here:
        String tarik = tftarik.getText();
        String saldolast = show.getText();
        show.setText(""+saldolast);
        int jmltarik = Integer.parseInt(tarik);
        int lastsaldo = Integer.parseInt(saldolast);
        int total = lastsaldo-jmltarik;
        show.setText(""+total);
    }//GEN-LAST:event_btarikActionPerformed

    private void btransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btransferActionPerformed
        // TODO add your handling code here:
        String transfer = tftransfer.getText();
        String saldolast = show.getText();
        show.setText(""+saldolast);
        int jmltransfer = Integer.parseInt(transfer);
        int lastsaldo = Integer.parseInt(saldolast);
        int total = lastsaldo-jmltransfer;
        show.setText(""+total);
    }//GEN-LAST:event_btransferActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public  void run() {
                new bank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bsaldo;
    private javax.swing.JButton bsetor;
    private javax.swing.JButton btarik;
    private javax.swing.JButton btransfer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel show;
    private javax.swing.JLabel show2;
    private javax.swing.JTextField tfsetor;
    private javax.swing.JTextField tftarik;
    private javax.swing.JTextField tftransfer;
    // End of variables declaration//GEN-END:variables

    private static class setVisible {

        public setVisible(boolean b) {
        }
    }
}
